#!/bin/bash
# sreport for account and X days ago
#
# Test for no command line input
if [ $# -eq 0 ]
  then
    echo "usage: suacct [acct] [days, default 30]"
    exit 1
fi

# Test for no Slurm module or native slurm
if [[ $(which squeue 2>&1 |grep "no squeue") ]];
  then
    echo "Slum required, please load a Slurm module and try again."
    exit 1
fi

if [[ -z $2 ]]; then days=30; else days=$2;fi
acct=$1
# do not need # if [[ $acct == *"@"* ]]; then match=`echo $user| awk -F@ '{print $1}'` ; else match=$user; fi
echo "SU used by account (allocation) $acct in the last $days days:"
sreport  -t hours -P cluster AccountUtilizationByUser start=`date +%Y-%m-%d -d "$days days ago"` tree acct=$acct |sed 1,4d
